'use strict';

module.exports.avoidSource = {
  //https://gist.github.com/Rub21/3aec0a2c704226db7746463694ed06c4
  'survey': true,
  'nearmap': true,
  'goo.gl/KHOCg': true,
  'USGS': true,
  'National Hydrography Dataset': true,
  'GPS': true,
  'extrapolation': true,
  'MML 2012': true,
  'legea544/2001': true,
  'yahoo': true,
  'ALPSMAP': true,
  'Landsat': true,
  'ourairports.com': true,
  'LPI': true,
  'lpis': true,
  'knowledge': true,
  'Protected Areas of Queensland - Boundaries Dated: 30-09-2010': true,
  'Lakewalker': true,
  'WMS': true,
  'cuzk': true,
  'uhul': true,
  'Moreton Bay Rail Project team public mail out - Feb 2015': true,
  'translink': true,
  'au.qld.dcdb_lite': true,
  'geoimage': true,
  'plan.at 2009': true,
  'basemap.at MaxRes 2012': true,
  'RABA-KGZ': true,
  'Institut für Militärisches Geowesen': true,
  'eea': true,
  'Készítette': true,
  'Union européenne': true,
  'corine': true,
  'ОУП': true,
  'Land Information Ontario': true,
  'HELP SERVICE': true,
  'Kolding Kommune': true,
  'NLS': true,
  'Tampereen Kaupunki': true,
  'geodata': true,
  'turistautak.hu': true,
  'Dana Kabupaten': true,
  'skp2osm': true,
  'lores': true,
  'catatrum': true,
  'http://www.cfa.org.py/': true,
  'NHD': true,
  'PGS': true,
  'Regione': true,
  'European Enviromental Agency CLC 2000': true,
  'European Urban Atlas': true,
  'PCN ortofoto_colore 2006 - autorizzazione 10687/TRI': true,
  'UDB60': true,
  'http://dati.emilia-romagna.it/dato/item/11-11-uso-del-suolo-2008.html': true,
  'openaerialmap': true,
  'MLIT, Japan': true,
  'GSImaps': true,
  'KSJ2': true,
  'http://www2.wagamachi-guide.com/toyokawa/': true,
  'photo': true,
  'Ventspils)': true,
  'USSR MAP': true,
  'Talsu novada teritorijas': true,
  'Dundagas': true,
  'Natura2000': true,
  'Kartverket': true,
  'dpwh': true,
  'ALOS-AV2': true,
  'Lasy Państwowe': true,
  'Starostwo Powiatowe w Kamieniu Pomorskim': true,
  'ump': true,
  'Geoportal': true,
  'WroclawGIS': true,
  'Poznań Ortofotomapa 2014': true,
  'rapideye': true,
  'GMES': true,
  'PRNG': true,
  'urbanatlas': true,
  'irs': true,
  'rgis': true,
  'highway buffers': true,
  'kosmosnimki': true,
  'СТП Ульяновской области': true,
  'OrbView': true,
  'kapor2': true,
  'Catastro': true,
  'PNOA': true,
  'ide.Sevilla': true,
  'ITACyL': true,
  'datos oficiales': true,
  'fercema': true,
  'b5m': true,
  'cartociudad': true,
  'Instituto Geográfico Nacional': true,
  'Ajuntament': true,
  'bulding': true,
  'Länsstyrelsen': true,
  'Ekonomiska kartan': true,
  'historical': true,
  'http://www.fs.fed.us/r6/data-library/gis/olympic/hydronet_meta.htm': true,
  'http://www.consrv.ca.gov/dlrp/fmmp/products/Pages/DownloadGISdata.aspx': true,
  'City': true,
  'http://www.co.fresno.ca.us/%5Cdepartmentpage.aspx?id=16313': true,
  'arcgis': true,
  'image': true,
  'http://forgottenfortcollins.com/stout_colorado/': true,
  'Riley County GIS': true,
  'note 435627': true,
  'Iowa DNR': true,
  'MetroGIS DataFinder (http://www.datafinder.org/metadata/parks_regional.htm)': true,
  'https://gis03.co.olmsted.mn.us/Property_Info_Public/default.aspx': true,
  'MGC': true,
  'wikipedia': true,
  'LandPro08': true,
  'USDA Forest Service Geodata Clearinghouse': true,
  'NCOnemap': true,
  'Athens-Clarke County': true,
  'http://www.tngis.org': true,
  'SFWMD Landcover 2008': true,
  'mapwise': true,
  'W&M GCA': true,
  'NJ2002LULC': true,
  'Plats': true,
  'MassGIS': true,
  'GRANIT': true,
  'www.franklinskiarea.com': true,
  'CT Department of Environmental Protection shapefile': true,
  'MGIS': true
};
