#!/usr/bin/env node
'use strict';

var filterUsers = require('./');

if (process.argv.length < 3) {
    console.log('Usage: osmlint-filterUsers <mbtiles path> <bbox>');
    return;
}

var mbtilesPath = process.argv[2];
var bbox = JSON.parse(process.argv[3]);

filterUsers(mbtilesPath, bbox);

