#!/usr/bin/env node
'use strict';

var bridgeOnNode = require('./');

if (process.argv.length < 3) {
    console.log('Usage: osmlint-bridgeOnNode <mbtiles path> <bbox>');
    return;
}

var mbtilesPath = process.argv[2];
var bbox = JSON.parse(process.argv[3]);

bridgeOnNode(mbtilesPath, bbox);

